version: "3.8"

services:
  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
    networks:
      - web2-net

  node1:
    build:
      context: .
      dockerfile: dockerfile.app
    container_name: node1
    networks:
      - web2-net

  node2:
    build:
      context: ./build-node2
      dockerfile: ../dockerfile.node
    container_name: node2
    networks:
      - web2-net

  node3:
    build:
      context: ./build-node3
      dockerfile: ../dockerfile.node
    container_name: node3
    networks:
      - web2-net

  node4:
    build:
      context: ./build-node4
      dockerfile: ../dockerfile.node
    container_name: node4
    networks:
      - web2-net

  node5:
    build:
      context: ./build-node5
      dockerfile: ../dockerfile.node
    container_name: node5
    networks:
      - web2-net

networks:
  web2-net:
    driver: bridge
